# Generated by Django 4.2.7 on 2025-08-12 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventregistration_price_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Réduction (%)'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix remisé'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_discount_active',
            field=models.BooleanField(default=False, verbose_name='Réduction active'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reminder_1d', 'Rappel J-1'), ('reminder_day', 'Rappel jour J'), ('update', 'Mise à jour'), ('thank_you', 'Remerciement')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.eventregistration')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'indexes': [models.Index(fields=['event', 'type'], name='events_noti_event_i_d9e6cf_idx'), models.Index(fields=['registration', 'type'], name='events_noti_registr_1cfa7b_idx')],
            },
        ),
    ]
