# Generated by Django 4.2.7 on 2025-08-13 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_tickettype_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('invite', 'Sur invitation')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('organizer', 'Organisateur'), ('participant', 'Participant'), ('guest', 'Invité')], default='participant', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
