# Generated by Django 4.2.7 on 2025-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_notificationlog_type_refundrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('organizer', 'Organisateur'), ('participant', 'Participant'), ('guest', 'Invité')], default='participant', max_length=20),
        ),
    ]
