# Generated by Django 4.2.7 on 2025-08-20 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_approval',
            field=models.CharField(choices=[('pending', "En attente d'approbation"), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='approved', max_length=20),
        ),
    ]
