# Generated by Django 4.2.7 on 2025-08-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_userprofile_approval_date_userprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la session')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre max de participants')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Participants actuels')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('date', models.DateField(verbose_name='Date de la session')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Choix obligatoire')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_types', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Type de session',
                'verbose_name_plural': 'Types de sessions',
                'ordering': ['date', 'start_time', 'display_order'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.sessiontype', verbose_name='Type de session'),
        ),
    ]
