# Generated by Django 4.2.7 on 2025-08-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_sessiontype_eventregistration_session_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Type de session', 'verbose_name_plural': 'Types de sessions'},
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='current_participants',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='start_time',
        ),
    ]
