# Generated by Django 4.2.7 on 2025-08-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_sessiontype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_waitlist',
            field=models.BooleanField(default=True, verbose_name="Activer la liste d'attente"),
        ),
    ]
