# Generated by Django 4.2.7 on 2025-08-25 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_add_enable_waitlist_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email de l'invité"),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='guest_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom complet de l'invité"),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone de l'invité"),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_guest_registration',
            field=models.BooleanField(default=False, verbose_name="Inscription d'invité"),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='unique_user_event_registration'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_email__isnull', False)), fields=('event', 'guest_email'), name='unique_guest_email_event_registration'),
        ),
    ]
