# Generated by Django 4.2.7 on 2025-09-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_guest_country'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_phone__isnull', False)), fields=('event', 'guest_phone'), name='unique_guest_phone_event_registration'),
        ),
    ]
