# Generated by Django 4.2.7 on 2025-09-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventregistration_unique_guest_phone_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Pays'),
        ),
    ]
