# Generated by Django 4.2.7 on 2025-09-02 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0020_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du rappel')),
                ('message', models.TextField(verbose_name='Message')),
                ('reminder_type', models.CharField(choices=[('general', 'Rappel général'), ('reminder', "Rappel d'événement"), ('update', 'Mise à jour'), ('cancellation', 'Annulation'), ('postponement', 'Report'), ('custom', 'Message personnalisé')], default='general', max_length=20, verbose_name='Type de rappel')),
                ('target_audience', models.CharField(choices=[('all', 'Tous les participants'), ('confirmed', 'Participants confirmés uniquement'), ('waitlisted', "Liste d'attente uniquement"), ('attended', 'Participants présents uniquement'), ('custom', 'Sélection personnalisée')], default='all', max_length=20, verbose_name='Audience cible')),
                ('send_email', models.BooleanField(default=True, verbose_name='Envoyer par email')),
                ('send_sms', models.BooleanField(default=True, verbose_name='Envoyer par SMS')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('sent', 'Envoyé'), ('failed', 'Échec')], default='draft', max_length=20, verbose_name='Statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi programmée")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Total destinataires')),
                ('emails_sent', models.PositiveIntegerField(default=0, verbose_name='Emails envoyés')),
                ('sms_sent', models.PositiveIntegerField(default=0, verbose_name='SMS envoyés')),
                ('emails_failed', models.PositiveIntegerField(default=0, verbose_name='Emails échoués')),
                ('sms_failed', models.PositiveIntegerField(default=0, verbose_name='SMS échoués')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('custom_recipients', models.ManyToManyField(blank=True, related_name='custom_reminders', to='events.eventregistration', verbose_name='Destinataires personnalisés')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reminders', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Rappel personnalisé',
                'verbose_name_plural': 'Rappels personnalisés',
                'ordering': ['-created_at'],
            },
        ),
    ]
