# Generated by Django 4.2.7 on 2025-09-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_customreminder'),
    ]

    operations = [
    ]
