# Generated by Django 4.2.7 on 2025-09-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20250902_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReminderRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reminder_recipients', to='events.eventregistration', verbose_name='Inscription')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_entries', to='events.customreminder', verbose_name='Rappel')),
            ],
            options={
                'verbose_name': 'Destinataire personnalisé',
                'verbose_name_plural': 'Destinataires personnalisés',
                'unique_together': {('reminder', 'registration')},
            },
        ),
    ]
