# Generated by Django 4.2.7 on 2025-09-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_add_customreminderrecipient_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='enable_waitlist',
            field=models.BooleanField(default=True, verbose_name="Activer la liste d'attente"),
        ),
    ]
