# Generated by Django 4.2.7 on 2025-09-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_tickettype_enable_waitlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='enable_waitlist',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='enable_waitlist',
        ),
    ]
