# Generated by Django 4.2.7 on 2025-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_remove_enable_waitlist_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_waitlist',
            field=models.BooleanField(default=True, verbose_name="Activer la liste d'attente pour les billets par défaut"),
        ),
    ]
